[package]
name = "jito-protos"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
bincode = "1.3.3"
prost = "0.8.0"
prost-types = "0.8.0"
tonic = "0.5.2"
solana-sdk = "1.14.7"

[build-dependencies]
tonic-build = "0.5.2"
